name: StreamWatchiOS
options:
  minimumXcodeGenVersion: 2.38.0
packages: {}
targets:
  StreamWatchiOS:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: Sources
      - path: Resources
        buildPhase: resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.lsam.streaming.streamwatch
        PRODUCT_NAME: StreamWatch
        SWIFT_VERSION: 5.0
        INFOPLIST_FILE: Resources/Info.plist
        DEVELOPMENT_TEAM: ""
    scheme:
      testTargets: []
