SELECT 'v_stream_studio_project_list' AS check_name, count(*) AS row_count
FROM streaming.v_stream_studio_project_list
UNION ALL
SELECT 'v_stream_studio_publish_history' AS check_name, count(*) AS row_count
FROM streaming.v_stream_studio_publish_history;

DO $$
DECLARE
  v_project record;
BEGIN
  SELECT * INTO v_project
  FROM streaming.fn_stream_studio_create_project(
    'ws-phase1-verify',
    'Service SQL Verify Project',
    'Generated by v6 verify',
    'verify-user',
    'en',
    'private'
  )
  LIMIT 1;

  RAISE NOTICE 'created project => % / %', v_project.creator_project_id, v_project.project_code;
END $$;

SELECT creator_project_id, project_code, project_title, project_status
FROM streaming.v_stream_studio_project_list
ORDER BY created_at DESC
LIMIT 3;
