#!/data/data/com.termux/files/usr/bin/bash
set +e
set +u

# ============================================================
# DRAFT ONLY: AICompanyManager switch to clean production
# Generated by ANU-ANX at 20260430_112208
# ============================================================
# This script is intended for the next approved phase.
# It changes production files.
# Do not run unless Boss approves controlled switch.
# ============================================================

APP_ROOT="/data/data/com.termux/files/home/03.civilization-development/03.business-os/AICompanyManager"
RUN_TS="20260430_112208"
SWITCH_RUN_DIR="$APP_ROOT/900.meta/switch_to_clean_production_${RUN_TS}"

INDEX_HTML="$APP_ROOT/index.html"
CURRENT_SERVER="$APP_ROOT/server/aicm-local-ui-api-server.mjs"
CLEAN_SERVER="$APP_ROOT/server/aicm-clean-v2-api-server.candidate.mjs"
PROPOSED_INDEX_SOURCE="/data/data/com.termux/files/home/03.civilization-development/03.business-os/AICompanyManager/900.meta/prepare_controlled_production_switch_20260430_112208/200_PROPOSED_INDEX_CLEAN_PRODUCTION.html"

mkdir -p "$SWITCH_RUN_DIR"

cp "$INDEX_HTML" "$SWITCH_RUN_DIR/index.before_clean_switch.html"
cp "$CURRENT_SERVER" "$SWITCH_RUN_DIR/aicm-local-ui-api-server.before_clean_switch.mjs"

cp "$CLEAN_SERVER" "$CURRENT_SERVER"
cp "$PROPOSED_INDEX_SOURCE" "$INDEX_HTML"

node --check "$CURRENT_SERVER"
SERVER_CHECK_CODE="$?"

node --check "$APP_ROOT/assets/js/aicm-production-core.js"
CORE_CHECK_CODE="$?"

if [ "$SERVER_CHECK_CODE" -ne 0 ] || [ "$CORE_CHECK_CODE" -ne 0 ]; then
  echo "CHECK FAILED. Rolling back."
  cp "$SWITCH_RUN_DIR/index.before_clean_switch.html" "$INDEX_HTML"
  cp "$SWITCH_RUN_DIR/aicm-local-ui-api-server.before_clean_switch.mjs" "$CURRENT_SERVER"
  exit 1
fi

if command -v pgrep >/dev/null 2>&1; then
  PIDS="$(pgrep -f "aicm-local-ui-api-server.mjs" 2>/dev/null)"
  if [ -n "$PIDS" ]; then
    echo "$PIDS" | while IFS= read -r pid; do
      [ -n "$pid" ] && kill -9 "$pid" 2>/dev/null
    done
    sleep 1
  fi
fi

cd "$APP_ROOT" || exit 1
nohup node "$CURRENT_SERVER" > "$SWITCH_RUN_DIR/server.log" 2>&1 &
SERVER_PID="$!"

sleep 2

curl -sS --max-time 10 "http://127.0.0.1:8794/api/aicm/v2/context?owner_civilization_id=00000000-0000-4000-8000-000000000001" > "$SWITCH_RUN_DIR/context.json" 2> "$SWITCH_RUN_DIR/context.err"
CURL_CODE="$?"

echo "SERVER_PID=$SERVER_PID"
echo "CURL_CODE=$CURL_CODE"
echo "OPEN_URL=http://127.0.0.1:8794/?v=${RUN_TS}_clean_production"
echo "BACKUP_INDEX=$SWITCH_RUN_DIR/index.before_clean_switch.html"
echo "BACKUP_SERVER=$SWITCH_RUN_DIR/aicm-local-ui-api-server.before_clean_switch.mjs"
echo "SWITCH_RUN_DIR=$SWITCH_RUN_DIR"
